### ISSUE TITLE
Renaming eve.elm

### ISSUE THREAD

**Issue by kachkaev** [gicentre/elm-vega#13]
Given that the project has been renamed in https://github.com/gicentre/elm-vega/pull/7, should not `src/eve.elm` be renamed too? There are still some occurences of `eve` left in the code.
https://github.com/gicentre/elm-vega/search?utf8=%E2%9C%93&q=eve

I can do that if you approve.

**Comment by jwoLondon** [comment]
I _think_ (but correct me if I'm wrong) that the only references to Eve are in the text of the documentation where we mention the library can be called Eve for short and in the name of the main  module.  As I understand it, the Elm convention for a package name in the form of "Elm-foo' is to call the main module in the package 'Foo or similar without the 'Elm-' prefix. In our case, it would be misleading to call the module 'Vega', so I think 'Eve' (a contraction of 'Elm' and 'Vega') makes sense.

**Comment by jwoLondon** [comment]
After face to face discussion, agreed that the advantages of renaming `Eve` to `Vega` outweigh disadvantages. Main module now `Vega` with all references to 'eve' removed.
