### ISSUE TITLE
Geo

### ISSUE THREAD

**Issue by kachkaev** [gicentre/elm-vega#35]
Geo feature is now merged to vega-lite (https://github.com/vega/vega-lite/pull/2734) and [2.1.0-beta](https://github.com/vega/vega-lite/releases) is out!

Looks like it's time to think of adding geo to elm-vega!

**Comment by jwoLondon** [comment]
Yes. Looks good and nicely integrated with the Vega-Lite model. I will integrate this and add the examples to the documentation soon.

**Comment by jwoLondon** [comment]
Geo functionality (GeoShape marks, projection, latitude/longitude/geojson types) now implemented along with the geo examples in vlTest-gallery.

Will close this issue although there are may be some changes in response the transition from Vega-Lite 2.1 beta to confirmed release.
