### ISSUE TITLE
How to remove legends ?

### ISSUE THREAD

**Issue by yormi** [gicentre/elm-vega#42]
Hi there !

I was just wondering if there is a way to remove the legends ?

Btw, your library is lovely to use. Thanks ! :)

**Comment by yormi** [comment]
Lovely ! Thank you for the quick reply !

Is it in the doc ? Otherwise I'd suggest to add it. Personnally, I just found in vega-lite doc:

> User can set the legend property of a mark property channel’s field definition to an object to customize legend properties or set legend to null to remove the legend.

and I was a bit confused on how to represent `null` in elm haha

**Comment by jwoLondon** [comment]
You are right about it not being obvious in the docs, so I've added this to the next release documentation (under the `color` function). 

In general,  where Vega-Lite says `null` elm-vega uses `[]` for lists, `""` for strings and `Nothing` for numeric values.

Thanks very much for raising this issue.

**Comment by yormi** [comment]
Great ! I looked at your commit and was wondering if the following:

> In general, where Vega-Lite says null elm-vega uses [] for lists, "" for strings and Nothing for numeric values.

apply to more than the legend and the axis. If yes, I'd suggest to add it in a general section in the beginning.

Thanks again for the tremendous work !
