### ISSUE TITLE
Possible to expose VegaLite.LabelledSpec ?

### ISSUE THREAD

**Issue by yormi** [gicentre/elm-vega#43]
It'll be nice to be able to use it to mute `elm-format` when extracting it to helper function to reuse :)

Cheers !

**Comment by jwoLondon** [comment]
Could you elaborate with a short example to illustrate the problem? I'm not sure I understand it yet.

Happy to expose `LabelledSpec` (which is currently just a `(String, Spec)` tuple) if we have a compelling use-case.

**Comment by yormi** [comment]
Sure ! Let me know if I missed something:

The graph I have so far is getting quite long in lines of code. I want to reuse some part of it like the Y position with few changes. What I did is extracting it to a function with a few args that allow to (`myPosition : X -> Y -> List LabelledSpec`).

Obviously, `LabelledSpec` is not exposed so I can't give a signature to that function. It's not a super big deal but allowing warning is a bad practice, right ?

Well, that was before, now that I know, I can still use `(String, Spec)` in the signature but it seems that it is implementation details if `LabelledSpec` is what you use in the api ?

What do you think ?

**Comment by jwoLondon** [comment]
Thanks for providing the example. I hadn't come across a need to expose `LabelledSpec` before as the most common cases for providing parameterised versions of spec generating functions have been data generation, for which `Data` was provided.

I've now exposed `LabelledSpec` in the next release. 

Thanks very much for raising this issue and providing an example.

**Comment by yormi** [comment]
Lovely !
