### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by hulufei** [gicentre/elm-vega#60]
Thanks for your working on this project.

As our team plan to use Elm in a new project, and Vega for our visualization, glad to find elm-vega exists, It'll be nice to upgrade to Elm 0.19.

**Comment by jwoLondon** [comment]
Elm-vega 4, with Elm 0.19 is now good to go. 

Full Vega coverage is supported with elm-vega, and full Vega-Lite coverage supported in the now separate package [elm-vegaLite](https://github.com/gicentre/elm-vegalite).

I will close this issue for now, but obviously if you spot any problems, please do raise them here on github.
