### ISSUE TITLE
`usermeta` section missing

### ISSUE THREAD

**Issue by anagrius** [gicentre/elm-vega#62]
At Humio we plan on using the `usermeta` section in vega specs to specify application specific properties e.g. the preprocessing the data needs before it is passed to Vega.
We use Elm and are looking at elm-vega (wonderful work btw). Currently the only no-go is the lack of custom usermeta which is defined in the vega JSON spec: https://vega.github.io/vega/docs/specification/

I would be happy to do a PR if you are strapped for time.

**Comment by jwoLondon** [comment]
Thanks for pointing this out. I will add this today (I have a few other updates to make so probably easier for me to incorporate into those, but thanks for your offer of a PR anyway).

**Comment by jwoLondon** [comment]
This has now been added in release 5.2.0. To add metadata, call `userMeta` with a list of tuples defining the metadata (key,value) pairs you wish to add. For example:

```elm
userMeta
    [ ( "Org", vStr "giCentre" )
    , ( "Date", vStr "2019-10-29" )
    , ( "Version", vNum 3.2 )
    ]
```

**Comment by anagrius** [comment]
Great stuff. Thanks Jo
