### ISSUE TITLE
Additional Properties - Bee Swarm Vega Example

### ISSUE THREAD

**Issue by ChrisWellsWood** [gicentre/elm-vega#65]
Hello, I'm trying to make a plot based on the bee swarm Vega example: https://vega.github.io/vega/examples/beeswarm-plot/. It requires the use of "additional properties" (discussed [here](https://github.com/vega/vega/issues/1142)). I can't see a way to encode these in `elm-vega`, is it possible? Thanks for your help.

**Comment by jwoLondon** [comment]
Yes, this can be achieved with [maCustom](https://package.elm-lang.org/packages/gicentre/elm-vega/latest/Vega#maCustom) to create a custom mark property.

In fact, the [beeswarm example](https://github.com/gicentre/elm-vega/blob/2b4e23d197b6558de82141e0a960cc47f8f7448b/examples/gallery/src/GalleryOther.elm#L566) is included in the elm-vega gallery to see it in action.
